# Generated by Django 3.2.2 on 2021-05-18 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otdel_name', models.TextField(max_length=1000, verbose_name='Отделение')),
                ('spec_name', models.TextField(max_length=1000, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otdel_name', models.TextField(max_length=1000, verbose_name='Отделение')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.otdel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(max_length=1000)),
                ('kredo', models.TextField(blank=True, max_length=1000)),
                ('otzyv', models.TextField(max_length=1000)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.specialnost')),
            ],
        ),
    ]
