# Generated by Django 3.2.2 on 2021-05-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otdel',
            name='spec_name',
        ),
    ]
