# Generated by Django 3.2.2 on 2021-05-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_otdel_spec_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnost',
            name='name',
            field=models.TextField(max_length=1000, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='specialnost',
            name='otdel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.otdel'),
        ),
    ]
