# Generated by Django 3.2.2 on 2021-05-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialnost',
            old_name='otdel_name',
            new_name='otdel',
        ),
    ]
