# Generated by Django 3.2.2 on 2021-05-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='otdel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.otdel'),
            preserve_default=False,
        ),
    ]
