# Generated by Django 3.2.2 on 2021-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_otdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='fio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='otdel',
            name='otdel_name',
            field=models.CharField(max_length=1000, verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='specialnost',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Специальность'),
        ),
    ]
