# Generated by Django 3.2.2 on 2021-06-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210610_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='fio',
            new_name='name',
        ),
    ]
