# Generated by Django 3.2.2 on 2021-06-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210610_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='ФИО'),
        ),
    ]
