# Generated by Django 3.2.2 on 2021-06-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='otdel',
        ),
        migrations.AlterField(
            model_name='card',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='core.category'),
        ),
    ]
