# Generated by Django 3.2.2 on 2021-06-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210616_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialnost',
            name='otdel',
        ),
        migrations.AlterField(
            model_name='card',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.DeleteModel(
            name='Otdel',
        ),
        migrations.DeleteModel(
            name='Specialnost',
        ),
    ]
