# Generated by Django 3.2.2 on 2021-06-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_spec_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='god_grad',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='специальность'),
        ),
    ]
