# Generated by Django 3.2.2 on 2021-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_card_god_grad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='god_grad',
            field=models.IntegerField(blank=True, default=2020, max_length=4, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
