# Generated by Django 3.2.2 on 2021-06-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_card_god_grad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.category', verbose_name='специальность'),
        ),
        migrations.AlterField(
            model_name='card',
            name='god_grad',
            field=models.IntegerField(blank=True, verbose_name='Год выпуска'),
        ),
    ]
